# Generated by Django 3.2.9 on 2021-11-25 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_review_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
    ]
