# Generated by Django 3.2.9 on 2021-11-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('No_Genre', '없음'), ('Action', '액션'), ('Adventure', '모험'), ('Animation', '애니메이션'), ('Comedy', '코미디'), ('Crime', '범죄'), ('Documentary', '다큐멘터리'), ('Drama', '드라마'), ('Family', '가족'), ('Fantasy', '판타지'), ('History', '역사'), ('Horror', '공포'), ('Music', '음악'), ('Mystery', '미스터리'), ('Romance', '로맨스'), ('Science_Fiction', 'SF'), ('TV_Movie', 'TV 영화'), ('Thriller', '스릴러'), ('War', '전쟁'), ('Western', '서부')], default='No_Genre', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('rank', models.IntegerField()),
                ('actor', models.TextField()),
                ('release_date', models.DateField()),
                ('poster_path', models.TextField()),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
