# Generated by Django 3.2.9 on 2021-11-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_pk',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
