# Generated by Django 3.2.9 on 2021-11-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_pk',
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('No_Genre', '없음'), ('Action', '액션'), ('Adventure', '모험'), ('Animation', '애니메이션'), ('Comedy', '코미디'), ('Crime', '범죄'), ('Documentary', '다큐멘터리'), ('Drama', '드라마'), ('Family', '가족'), ('Fantasy', '판타지'), ('History', '역사'), ('Horror', '공포'), ('Music', '음악'), ('Mystery', '미스터리'), ('Romance', '로맨스'), ('Science_Fiction', 'SF'), ('TV_Movie', 'TV 영화'), ('Thriller', '스릴러'), ('War', '전쟁'), ('Western', '서부')], default='No_Genre', max_length=50),
        ),
    ]
