# Generated by Django 3.2.9 on 2021-11-19 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_auto_20211119_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranking',
            new_name='UserMovie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='users',
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
